// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_2d1iJUx11uAmtv5Lsce6imO7Dx1lMPc',
    appId: '1:772559983254:web:56a76224de57467d5468b7',
    messagingSenderId: '772559983254',
    projectId: 'jobster-c0230',
    authDomain: 'jobster-c0230.firebaseapp.com',
    storageBucket: 'jobster-c0230.firebasestorage.app',
    measurementId: 'G-P1S34LN5F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVAuzhqWOCEvUMI9CIdrv5HyrQ-saBw0o',
    appId: '1:772559983254:android:d5b978abc0a108575468b7',
    messagingSenderId: '772559983254',
    projectId: 'jobster-c0230',
    storageBucket: 'jobster-c0230.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCAvQ8VtV3bRvimI1XAi99Ubic-zY30LY',
    appId: '1:772559983254:ios:71452183e16779d95468b7',
    messagingSenderId: '772559983254',
    projectId: 'jobster-c0230',
    storageBucket: 'jobster-c0230.firebasestorage.app',
    iosBundleId: 'com.example.jobster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCAvQ8VtV3bRvimI1XAi99Ubic-zY30LY',
    appId: '1:772559983254:ios:71452183e16779d95468b7',
    messagingSenderId: '772559983254',
    projectId: 'jobster-c0230',
    storageBucket: 'jobster-c0230.firebasestorage.app',
    iosBundleId: 'com.example.jobster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_2d1iJUx11uAmtv5Lsce6imO7Dx1lMPc',
    appId: '1:772559983254:web:a82ec9b39f280a425468b7',
    messagingSenderId: '772559983254',
    projectId: 'jobster-c0230',
    authDomain: 'jobster-c0230.firebaseapp.com',
    storageBucket: 'jobster-c0230.firebasestorage.app',
    measurementId: 'G-5B05DC323G',
  );
}


